apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-list
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-list
  template:
    metadata:
      labels:
        app: car-list
    spec:
      containers:
        - name: nextjs-container
          image: devdk3515/cars_05:latest
          ports:
            - containerPort: 5000
